#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import re

# Variables for 'waf dist'
APPNAME = 'midi_gate-psi.lv2'
VERSION = '0.3.0'

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    opt.load('compiler_cxx')
    opt.load('compiler_cxx')
    autowaf.set_options(opt)

def configure(conf):
    conf.load('compiler_c')
    conf.load('compiler_cxx')
    autowaf.configure(conf)
    autowaf.set_c99_mode(conf)
    autowaf.display_header('Midigate Configuration')

    if not autowaf.is_child():
        autowaf.check_pkg(conf, 'lv2', uselib_store='LV2')
        
    autowaf.check_pkg(conf, 'ntk', uselib_store='NTK',
        mandatory=True)    
    autowaf.display_msg(conf, 'LV2 bundle directory', conf.env.LV2DIR)
    conf.env.CXXFLAGS.append('-DLV2_DIR="'+conf.env.LV2DIR+'"')
    print('')

def build(bld):
    bundle = 'midi_gate-psi.lv2'

    # Make a pattern for shared objects without the 'lib' prefix
    module_pat = re.sub('^lib', '', bld.env.cshlib_PATTERN)
    module_ext = module_pat[module_pat.rfind('.'):]

    # Build manifest.ttl by substitution (for portable lib extension)
    bld(features     = 'subst',
        source       = 'manifest.ttl.in',
        target       = '%s/%s' % (bundle, 'manifest.ttl'),
        install_path = '${LV2DIR}/%s' % bundle,
        LIB_EXT      = module_ext)

    # Copy other data files to build bundle
    for i in ['midi_gate.ttl','README.md','../UI/knob.png']:
        bld(features     = 'subst',
            is_copy      = True,
            source       = i,
            target       = '%s/%s' % (bundle, i),
            install_path = '${LV2DIR}/%s' % bundle)

    includes = ['/usr/include/ntk','/usr/include','../common','../UI']

    # Build plugin library
    obj = bld(features     = 'c cshlib',
              source       = ['midi_gate.c'],
              name         = ['midi_gate'],
              target       = '%s/midi_gate' % bundle,
              install_path = '${LV2DIR}/%s' % bundle,
              uselib       = ['LV2','M'],
              cflags       = '-Wall -std=c++11',
              includes     = includes)
    obj.env.cshlib_PATTERN = module_pat
    obj.env.cxxshlib_PATTERN = module_pat
    # Build plugin UI library
    obj = bld(features     = 'cxx cxxshlib',
              source       = ['../UI/psiDialX.cxx','midi_gate_widget.cxx','midi_gate_ui.cxx'],
              name         = 'midi_gate_ui',
              target       = '%s/midi_gate_ui' % bundle,
              install_path = '${LV2DIR}/%s' % bundle,
              uselib       = 'LV2 M NTK NTK_IMAGES',
              cflags       = '-Wall -std=c++11',
              includes     = includes)
    obj.env.cxxshlib_PATTERN = module_pat

